//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweaWebService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://swea.riksbank.se/xsd")]
    public partial class ServiceException
    {
        
        private ServiceExceptionType serviceException1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServiceException", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public ServiceExceptionType ServiceException1
        {
            get
            {
                return this.serviceException1Field;
            }
            set
            {
                this.serviceException1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class ServiceExceptionType : Exception
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceExceptionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class Exception
    {
        
        private object exception1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exception", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public object Exception1
        {
            get
            {
                return this.exception1Field;
            }
            set
            {
                this.exception1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class SearchRequestParameters
    {
        
        private AggregateMethodType aggregateMethodField;
        
        private System.DateTime datefromField;
        
        private System.DateTime datetoField;
        
        private LanguageType languageidField;
        
        private bool minField;
        
        private bool avgField;
        
        private bool maxField;
        
        private bool ultimoField;
        
        private SearchGroupSeries[] searchGroupSeriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AggregateMethodType aggregateMethod
        {
            get
            {
                return this.aggregateMethodField;
            }
            set
            {
                this.aggregateMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime datefrom
        {
            get
            {
                return this.datefromField;
            }
            set
            {
                this.datefromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime dateto
        {
            get
            {
                return this.datetoField;
            }
            set
            {
                this.datetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public LanguageType languageid
        {
            get
            {
                return this.languageidField;
            }
            set
            {
                this.languageidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool avg
        {
            get
            {
                return this.avgField;
            }
            set
            {
                this.avgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool ultimo
        {
            get
            {
                return this.ultimoField;
            }
            set
            {
                this.ultimoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("searchGroupSeries", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public SearchGroupSeries[] searchGroupSeries
        {
            get
            {
                return this.searchGroupSeriesField;
            }
            set
            {
                this.searchGroupSeriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public enum AggregateMethodType
    {
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        Q,
        
        /// <remarks/>
        Y,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public enum LanguageType
    {
        
        /// <remarks/>
        en,
        
        /// <remarks/>
        sv,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class SearchGroupSeries
    {
        
        private string groupidField;
        
        private string seriesidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string groupid
        {
            get
            {
                return this.groupidField;
            }
            set
            {
                this.groupidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string seriesid
        {
            get
            {
                return this.seriesidField;
            }
            set
            {
                this.seriesidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class CalendarDay
    {
        
        private string bankdayField;
        
        private System.Nullable<System.DateTime> caldateField;
        
        private string weekField;
        
        private int weekyearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string bankday
        {
            get
            {
                return this.bankdayField;
            }
            set
            {
                this.bankdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> caldate
        {
            get
            {
                return this.caldateField;
            }
            set
            {
                this.caldateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string week
        {
            get
            {
                return this.weekField;
            }
            set
            {
                this.weekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int weekyear
        {
            get
            {
                return this.weekyearField;
            }
            set
            {
                this.weekyearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class Series
    {
        
        private System.Nullable<System.DateTime> datefromField;
        
        private bool datefromFieldSpecified;
        
        private System.Nullable<System.DateTime> datetoField;
        
        private bool datetoFieldSpecified;
        
        private string seriesdescriptionField;
        
        private string seriesidField;
        
        private string seriesnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> datefrom
        {
            get
            {
                return this.datefromField;
            }
            set
            {
                this.datefromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datefromSpecified
        {
            get
            {
                return this.datefromFieldSpecified;
            }
            set
            {
                this.datefromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> dateto
        {
            get
            {
                return this.datetoField;
            }
            set
            {
                this.datetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datetoSpecified
        {
            get
            {
                return this.datetoFieldSpecified;
            }
            set
            {
                this.datetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string seriesdescription
        {
            get
            {
                return this.seriesdescriptionField;
            }
            set
            {
                this.seriesdescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string seriesid
        {
            get
            {
                return this.seriesidField;
            }
            set
            {
                this.seriesidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string seriesname
        {
            get
            {
                return this.seriesnameField;
            }
            set
            {
                this.seriesnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class CrossResultSeries
    {
        
        private string seriesid1Field;
        
        private string seriesid2Field;
        
        private string seriesnameField;
        
        private ResultRow[] resultrowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string seriesid1
        {
            get
            {
                return this.seriesid1Field;
            }
            set
            {
                this.seriesid1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string seriesid2
        {
            get
            {
                return this.seriesid2Field;
            }
            set
            {
                this.seriesid2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string seriesname
        {
            get
            {
                return this.seriesnameField;
            }
            set
            {
                this.seriesnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultrows", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public ResultRow[] resultrows
        {
            get
            {
                return this.resultrowsField;
            }
            set
            {
                this.resultrowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class ResultRow
    {
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private string periodField;
        
        private System.Nullable<double> minField;
        
        private bool minFieldSpecified;
        
        private System.Nullable<double> averageField;
        
        private bool averageFieldSpecified;
        
        private System.Nullable<double> maxField;
        
        private bool maxFieldSpecified;
        
        private System.Nullable<double> ultimoField;
        
        private bool ultimoFieldSpecified;
        
        private System.Nullable<double> valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<double> min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minSpecified
        {
            get
            {
                return this.minFieldSpecified;
            }
            set
            {
                this.minFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<double> average
        {
            get
            {
                return this.averageField;
            }
            set
            {
                this.averageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool averageSpecified
        {
            get
            {
                return this.averageFieldSpecified;
            }
            set
            {
                this.averageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<double> max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSpecified
        {
            get
            {
                return this.maxFieldSpecified;
            }
            set
            {
                this.maxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<double> ultimo
        {
            get
            {
                return this.ultimoField;
            }
            set
            {
                this.ultimoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ultimoSpecified
        {
            get
            {
                return this.ultimoFieldSpecified;
            }
            set
            {
                this.ultimoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<double> value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class CrossResultGroup
    {
        
        private string groupidField;
        
        private string groupnameField;
        
        private CrossResultSeries[] seriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string groupid
        {
            get
            {
                return this.groupidField;
            }
            set
            {
                this.groupidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string groupname
        {
            get
            {
                return this.groupnameField;
            }
            set
            {
                this.groupnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("series", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public CrossResultSeries[] series
        {
            get
            {
                return this.seriesField;
            }
            set
            {
                this.seriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class CrossResult
    {
        
        private System.Nullable<System.DateTime> datefromField;
        
        private bool datefromFieldSpecified;
        
        private System.Nullable<System.DateTime> datetoField;
        
        private bool datetoFieldSpecified;
        
        private string informationtextField;
        
        private CrossResultGroup[] groupsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> datefrom
        {
            get
            {
                return this.datefromField;
            }
            set
            {
                this.datefromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datefromSpecified
        {
            get
            {
                return this.datefromFieldSpecified;
            }
            set
            {
                this.datefromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> dateto
        {
            get
            {
                return this.datetoField;
            }
            set
            {
                this.datetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datetoSpecified
        {
            get
            {
                return this.datetoFieldSpecified;
            }
            set
            {
                this.datetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string informationtext
        {
            get
            {
                return this.informationtextField;
            }
            set
            {
                this.informationtextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groups", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public CrossResultGroup[] groups
        {
            get
            {
                return this.groupsField;
            }
            set
            {
                this.groupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class ResultSeries
    {
        
        private string seriesidField;
        
        private string seriesnameField;
        
        private System.Nullable<double> unitField;
        
        private bool unitFieldSpecified;
        
        private ResultRow[] resultrowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string seriesid
        {
            get
            {
                return this.seriesidField;
            }
            set
            {
                this.seriesidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string seriesname
        {
            get
            {
                return this.seriesnameField;
            }
            set
            {
                this.seriesnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<double> unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitSpecified
        {
            get
            {
                return this.unitFieldSpecified;
            }
            set
            {
                this.unitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultrows", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public ResultRow[] resultrows
        {
            get
            {
                return this.resultrowsField;
            }
            set
            {
                this.resultrowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class ResultGroup
    {
        
        private string groupidField;
        
        private string groupnameField;
        
        private ResultSeries[] seriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string groupid
        {
            get
            {
                return this.groupidField;
            }
            set
            {
                this.groupidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string groupname
        {
            get
            {
                return this.groupnameField;
            }
            set
            {
                this.groupnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("series", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public ResultSeries[] series
        {
            get
            {
                return this.seriesField;
            }
            set
            {
                this.seriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class Result
    {
        
        private System.Nullable<System.DateTime> datefromField;
        
        private bool datefromFieldSpecified;
        
        private System.Nullable<System.DateTime> datetoField;
        
        private bool datetoFieldSpecified;
        
        private string informationtextField;
        
        private ResultGroup[] groupsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> datefrom
        {
            get
            {
                return this.datefromField;
            }
            set
            {
                this.datefromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datefromSpecified
        {
            get
            {
                return this.datefromFieldSpecified;
            }
            set
            {
                this.datefromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> dateto
        {
            get
            {
                return this.datetoField;
            }
            set
            {
                this.datetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datetoSpecified
        {
            get
            {
                return this.datetoFieldSpecified;
            }
            set
            {
                this.datetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string informationtext
        {
            get
            {
                return this.informationtextField;
            }
            set
            {
                this.informationtextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groups", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public ResultGroup[] groups
        {
            get
            {
                return this.groupsField;
            }
            set
            {
                this.groupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class Group
    {
        
        private string groupdescriptionField;
        
        private int groupidField;
        
        private bool groupidFieldSpecified;
        
        private string groupnameField;
        
        private string languageidField;
        
        private System.Nullable<int> parentgroupidField;
        
        private bool parentgroupidFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string groupdescription
        {
            get
            {
                return this.groupdescriptionField;
            }
            set
            {
                this.groupdescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int groupid
        {
            get
            {
                return this.groupidField;
            }
            set
            {
                this.groupidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupidSpecified
        {
            get
            {
                return this.groupidFieldSpecified;
            }
            set
            {
                this.groupidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string groupname
        {
            get
            {
                return this.groupnameField;
            }
            set
            {
                this.groupnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string languageid
        {
            get
            {
                return this.languageidField;
            }
            set
            {
                this.languageidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<int> parentgroupid
        {
            get
            {
                return this.parentgroupidField;
            }
            set
            {
                this.parentgroupidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parentgroupidSpecified
        {
            get
            {
                return this.parentgroupidFieldSpecified;
            }
            set
            {
                this.parentgroupidFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class CrossRequestParameters
    {
        
        private AggregateMethodType aggregateMethodField;
        
        private CurrencyCrossPair[] crossPairField;
        
        private System.Nullable<System.DateTime> datefromField;
        
        private System.Nullable<System.DateTime> datetoField;
        
        private System.Nullable<LanguageType> languageidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AggregateMethodType aggregateMethod
        {
            get
            {
                return this.aggregateMethodField;
            }
            set
            {
                this.aggregateMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("crossPair", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CurrencyCrossPair[] crossPair
        {
            get
            {
                return this.crossPairField;
            }
            set
            {
                this.crossPairField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> datefrom
        {
            get
            {
                return this.datefromField;
            }
            set
            {
                this.datefromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> dateto
        {
            get
            {
                return this.datetoField;
            }
            set
            {
                this.datetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<LanguageType> languageid
        {
            get
            {
                return this.languageidField;
            }
            set
            {
                this.languageidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class CurrencyCrossPair
    {
        
        private string seriesid1Field;
        
        private string seriesid2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string seriesid1
        {
            get
            {
                return this.seriesid1Field;
            }
            set
            {
                this.seriesid1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string seriesid2
        {
            get
            {
                return this.seriesid2Field;
            }
            set
            {
                this.seriesid2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
    public partial class GroupSeries
    {
        
        private System.Nullable<System.DateTime> datefromField;
        
        private bool datefromFieldSpecified;
        
        private System.Nullable<System.DateTime> datetoField;
        
        private bool datetoFieldSpecified;
        
        private string descriptionField;
        
        private string groupidField;
        
        private string longdescriptionField;
        
        private string seriesidField;
        
        private string shortdescriptionField;
        
        private string sourceField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> datefrom
        {
            get
            {
                return this.datefromField;
            }
            set
            {
                this.datefromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datefromSpecified
        {
            get
            {
                return this.datefromFieldSpecified;
            }
            set
            {
                this.datefromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> dateto
        {
            get
            {
                return this.datetoField;
            }
            set
            {
                this.datetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datetoSpecified
        {
            get
            {
                return this.datetoFieldSpecified;
            }
            set
            {
                this.datetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string groupid
        {
            get
            {
                return this.groupidField;
            }
            set
            {
                this.groupidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string longdescription
        {
            get
            {
                return this.longdescriptionField;
            }
            set
            {
                this.longdescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string seriesid
        {
            get
            {
                return this.seriesidField;
            }
            set
            {
                this.seriesidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string shortdescription
        {
            get
            {
                return this.shortdescriptionField;
            }
            set
            {
                this.shortdescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://swea.riksbank.se/ws", ConfigurationName="SweaWebService.SweaWebServicePortType")]
    public interface SweaWebServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getInterestAndExchangeNames", ReplyAction="urn:getInterestAndExchangeNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SweaWebService.ServiceException), Action="urn:getInterestAndExchangeNamesServiceException", Name="ServiceException", Namespace="http://swea.riksbank.se/xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CalendarDay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Series))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        System.Threading.Tasks.Task<SweaWebService.getInterestAndExchangeNamesResponse> getInterestAndExchangeNamesAsync(SweaWebService.getInterestAndExchangeNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getMonthlyAverageExchangeRates", ReplyAction="urn:getMonthlyAverageExchangeRatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SweaWebService.ServiceException), Action="urn:getMonthlyAverageExchangeRatesServiceException", Name="ServiceException", Namespace="http://swea.riksbank.se/xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CalendarDay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Series))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        System.Threading.Tasks.Task<SweaWebService.getMonthlyAverageExchangeRatesResponse> getMonthlyAverageExchangeRatesAsync(SweaWebService.getMonthlyAverageExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getInterestAndExchangeGroupNames", ReplyAction="urn:getInterestAndExchangeGroupNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SweaWebService.ServiceException), Action="urn:getInterestAndExchangeGroupNamesServiceException", Name="ServiceException", Namespace="http://swea.riksbank.se/xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CalendarDay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Series))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        System.Threading.Tasks.Task<SweaWebService.getInterestAndExchangeGroupNamesResponse> getInterestAndExchangeGroupNamesAsync(SweaWebService.getInterestAndExchangeGroupNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCrossRates", ReplyAction="urn:getCrossRatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SweaWebService.ServiceException), Action="urn:getCrossRatesServiceException", Name="ServiceException", Namespace="http://swea.riksbank.se/xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CalendarDay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Series))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        System.Threading.Tasks.Task<SweaWebService.getCrossRatesResponse> getCrossRatesAsync(SweaWebService.getCrossRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAllCrossNames", ReplyAction="urn:getAllCrossNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SweaWebService.ServiceException), Action="urn:getAllCrossNamesServiceException", Name="ServiceException", Namespace="http://swea.riksbank.se/xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CalendarDay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Series))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        System.Threading.Tasks.Task<SweaWebService.getAllCrossNamesResponse> getAllCrossNamesAsync(SweaWebService.getAllCrossNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCalendarDays", ReplyAction="urn:getCalendarDaysResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SweaWebService.ServiceException), Action="urn:getCalendarDaysServiceException", Name="ServiceException", Namespace="http://swea.riksbank.se/xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CalendarDay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Series))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        System.Threading.Tasks.Task<SweaWebService.getCalendarDaysResponse> getCalendarDaysAsync(SweaWebService.getCalendarDaysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAnnualAverageExchangeRates", ReplyAction="urn:getAnnualAverageExchangeRatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SweaWebService.ServiceException), Action="urn:getAnnualAverageExchangeRatesServiceException", Name="ServiceException", Namespace="http://swea.riksbank.se/xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CalendarDay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Series))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        System.Threading.Tasks.Task<SweaWebService.getAnnualAverageExchangeRatesResponse> getAnnualAverageExchangeRatesAsync(SweaWebService.getAnnualAverageExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getInterestAndExchangeRates", ReplyAction="urn:getInterestAndExchangeRatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SweaWebService.ServiceException), Action="urn:getInterestAndExchangeRatesServiceException", Name="ServiceException", Namespace="http://swea.riksbank.se/xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CalendarDay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Series))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        System.Threading.Tasks.Task<SweaWebService.getInterestAndExchangeRatesResponse> getInterestAndExchangeRatesAsync(SweaWebService.getInterestAndExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getLatestInterestAndExchangeRates", ReplyAction="urn:getLatestInterestAndExchangeRatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SweaWebService.ServiceException), Action="urn:getLatestInterestAndExchangeRatesServiceException", Name="ServiceException", Namespace="http://swea.riksbank.se/xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CalendarDay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Series))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossRequestParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        System.Threading.Tasks.Task<SweaWebService.getLatestInterestAndExchangeRatesResponse> getLatestInterestAndExchangeRatesAsync(SweaWebService.getLatestInterestAndExchangeRatesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInterestAndExchangeNames", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getInterestAndExchangeNamesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int groupid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SweaWebService.LanguageType languageid;
        
        public getInterestAndExchangeNamesRequest()
        {
        }
        
        public getInterestAndExchangeNamesRequest(int groupid, SweaWebService.LanguageType languageid)
        {
            this.groupid = groupid;
            this.languageid = languageid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInterestAndExchangeNamesResponse", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getInterestAndExchangeNamesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SweaWebService.GroupSeries[] @return;
        
        public getInterestAndExchangeNamesResponse()
        {
        }
        
        public getInterestAndExchangeNamesResponse(SweaWebService.GroupSeries[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMonthlyAverageExchangeRates", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getMonthlyAverageExchangeRatesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int month;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SweaWebService.LanguageType languageid;
        
        public getMonthlyAverageExchangeRatesRequest()
        {
        }
        
        public getMonthlyAverageExchangeRatesRequest(int year, int month, SweaWebService.LanguageType languageid)
        {
            this.year = year;
            this.month = month;
            this.languageid = languageid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMonthlyAverageExchangeRatesResponse", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getMonthlyAverageExchangeRatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SweaWebService.Result @return;
        
        public getMonthlyAverageExchangeRatesResponse()
        {
        }
        
        public getMonthlyAverageExchangeRatesResponse(SweaWebService.Result @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInterestAndExchangeGroupNames", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getInterestAndExchangeGroupNamesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SweaWebService.LanguageType languageid;
        
        public getInterestAndExchangeGroupNamesRequest()
        {
        }
        
        public getInterestAndExchangeGroupNamesRequest(SweaWebService.LanguageType languageid)
        {
            this.languageid = languageid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInterestAndExchangeGroupNamesResponse", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getInterestAndExchangeGroupNamesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SweaWebService.Group[] @return;
        
        public getInterestAndExchangeGroupNamesResponse()
        {
        }
        
        public getInterestAndExchangeGroupNamesResponse(SweaWebService.Group[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCrossRates", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getCrossRatesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SweaWebService.CrossRequestParameters crossRequestParameters;
        
        public getCrossRatesRequest()
        {
        }
        
        public getCrossRatesRequest(SweaWebService.CrossRequestParameters crossRequestParameters)
        {
            this.crossRequestParameters = crossRequestParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCrossRatesResponse", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getCrossRatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SweaWebService.CrossResult @return;
        
        public getCrossRatesResponse()
        {
        }
        
        public getCrossRatesResponse(SweaWebService.CrossResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCrossNames", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getAllCrossNamesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SweaWebService.LanguageType languageid;
        
        public getAllCrossNamesRequest()
        {
        }
        
        public getAllCrossNamesRequest(SweaWebService.LanguageType languageid)
        {
            this.languageid = languageid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCrossNamesResponse", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getAllCrossNamesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SweaWebService.Series[] @return;
        
        public getAllCrossNamesResponse()
        {
        }
        
        public getAllCrossNamesResponse(SweaWebService.Series[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCalendarDays", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getCalendarDaysRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime datefrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime dateto;
        
        public getCalendarDaysRequest()
        {
        }
        
        public getCalendarDaysRequest(System.DateTime datefrom, System.DateTime dateto)
        {
            this.datefrom = datefrom;
            this.dateto = dateto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCalendarDaysResponse", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getCalendarDaysResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SweaWebService.CalendarDay[] @return;
        
        public getCalendarDaysResponse()
        {
        }
        
        public getCalendarDaysResponse(SweaWebService.CalendarDay[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAnnualAverageExchangeRates", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getAnnualAverageExchangeRatesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int month;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SweaWebService.LanguageType languageid;
        
        public getAnnualAverageExchangeRatesRequest()
        {
        }
        
        public getAnnualAverageExchangeRatesRequest(int year, int month, SweaWebService.LanguageType languageid)
        {
            this.year = year;
            this.month = month;
            this.languageid = languageid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAnnualAverageExchangeRatesResponse", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getAnnualAverageExchangeRatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SweaWebService.Result @return;
        
        public getAnnualAverageExchangeRatesResponse()
        {
        }
        
        public getAnnualAverageExchangeRatesResponse(SweaWebService.Result @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInterestAndExchangeRates", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getInterestAndExchangeRatesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SweaWebService.SearchRequestParameters searchRequestParameters;
        
        public getInterestAndExchangeRatesRequest()
        {
        }
        
        public getInterestAndExchangeRatesRequest(SweaWebService.SearchRequestParameters searchRequestParameters)
        {
            this.searchRequestParameters = searchRequestParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInterestAndExchangeRatesResponse", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getInterestAndExchangeRatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SweaWebService.Result @return;
        
        public getInterestAndExchangeRatesResponse()
        {
        }
        
        public getInterestAndExchangeRatesResponse(SweaWebService.Result @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLatestInterestAndExchangeRates", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getLatestInterestAndExchangeRatesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SweaWebService.LanguageType languageid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("seriesid", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] seriesid;
        
        public getLatestInterestAndExchangeRatesRequest()
        {
        }
        
        public getLatestInterestAndExchangeRatesRequest(SweaWebService.LanguageType languageid, string[] seriesid)
        {
            this.languageid = languageid;
            this.seriesid = seriesid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLatestInterestAndExchangeRatesResponse", WrapperNamespace="http://swea.riksbank.se/xsd", IsWrapped=true)]
    public partial class getLatestInterestAndExchangeRatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swea.riksbank.se/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SweaWebService.Result @return;
        
        public getLatestInterestAndExchangeRatesResponse()
        {
        }
        
        public getLatestInterestAndExchangeRatesResponse(SweaWebService.Result @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SweaWebServicePortTypeChannel : SweaWebService.SweaWebServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SweaWebServicePortTypeClient : System.ServiceModel.ClientBase<SweaWebService.SweaWebServicePortType>, SweaWebService.SweaWebServicePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SweaWebServicePortTypeClient() : 
                base(SweaWebServicePortTypeClient.GetDefaultBinding(), SweaWebServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SweaWebServiceHttpSoap12Endpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SweaWebServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(SweaWebServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), SweaWebServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SweaWebServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SweaWebServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SweaWebServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SweaWebServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SweaWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SweaWebService.getInterestAndExchangeNamesResponse> SweaWebService.SweaWebServicePortType.getInterestAndExchangeNamesAsync(SweaWebService.getInterestAndExchangeNamesRequest request)
        {
            return base.Channel.getInterestAndExchangeNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SweaWebService.getInterestAndExchangeNamesResponse> getInterestAndExchangeNamesAsync(int groupid, SweaWebService.LanguageType languageid)
        {
            SweaWebService.getInterestAndExchangeNamesRequest inValue = new SweaWebService.getInterestAndExchangeNamesRequest();
            inValue.groupid = groupid;
            inValue.languageid = languageid;
            return ((SweaWebService.SweaWebServicePortType)(this)).getInterestAndExchangeNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SweaWebService.getMonthlyAverageExchangeRatesResponse> SweaWebService.SweaWebServicePortType.getMonthlyAverageExchangeRatesAsync(SweaWebService.getMonthlyAverageExchangeRatesRequest request)
        {
            return base.Channel.getMonthlyAverageExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SweaWebService.getMonthlyAverageExchangeRatesResponse> getMonthlyAverageExchangeRatesAsync(int year, int month, SweaWebService.LanguageType languageid)
        {
            SweaWebService.getMonthlyAverageExchangeRatesRequest inValue = new SweaWebService.getMonthlyAverageExchangeRatesRequest();
            inValue.year = year;
            inValue.month = month;
            inValue.languageid = languageid;
            return ((SweaWebService.SweaWebServicePortType)(this)).getMonthlyAverageExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SweaWebService.getInterestAndExchangeGroupNamesResponse> SweaWebService.SweaWebServicePortType.getInterestAndExchangeGroupNamesAsync(SweaWebService.getInterestAndExchangeGroupNamesRequest request)
        {
            return base.Channel.getInterestAndExchangeGroupNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SweaWebService.getInterestAndExchangeGroupNamesResponse> getInterestAndExchangeGroupNamesAsync(SweaWebService.LanguageType languageid)
        {
            SweaWebService.getInterestAndExchangeGroupNamesRequest inValue = new SweaWebService.getInterestAndExchangeGroupNamesRequest();
            inValue.languageid = languageid;
            return ((SweaWebService.SweaWebServicePortType)(this)).getInterestAndExchangeGroupNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SweaWebService.getCrossRatesResponse> SweaWebService.SweaWebServicePortType.getCrossRatesAsync(SweaWebService.getCrossRatesRequest request)
        {
            return base.Channel.getCrossRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SweaWebService.getCrossRatesResponse> getCrossRatesAsync(SweaWebService.CrossRequestParameters crossRequestParameters)
        {
            SweaWebService.getCrossRatesRequest inValue = new SweaWebService.getCrossRatesRequest();
            inValue.crossRequestParameters = crossRequestParameters;
            return ((SweaWebService.SweaWebServicePortType)(this)).getCrossRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SweaWebService.getAllCrossNamesResponse> SweaWebService.SweaWebServicePortType.getAllCrossNamesAsync(SweaWebService.getAllCrossNamesRequest request)
        {
            return base.Channel.getAllCrossNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SweaWebService.getAllCrossNamesResponse> getAllCrossNamesAsync(SweaWebService.LanguageType languageid)
        {
            SweaWebService.getAllCrossNamesRequest inValue = new SweaWebService.getAllCrossNamesRequest();
            inValue.languageid = languageid;
            return ((SweaWebService.SweaWebServicePortType)(this)).getAllCrossNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SweaWebService.getCalendarDaysResponse> SweaWebService.SweaWebServicePortType.getCalendarDaysAsync(SweaWebService.getCalendarDaysRequest request)
        {
            return base.Channel.getCalendarDaysAsync(request);
        }
        
        public System.Threading.Tasks.Task<SweaWebService.getCalendarDaysResponse> getCalendarDaysAsync(System.DateTime datefrom, System.DateTime dateto)
        {
            SweaWebService.getCalendarDaysRequest inValue = new SweaWebService.getCalendarDaysRequest();
            inValue.datefrom = datefrom;
            inValue.dateto = dateto;
            return ((SweaWebService.SweaWebServicePortType)(this)).getCalendarDaysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SweaWebService.getAnnualAverageExchangeRatesResponse> SweaWebService.SweaWebServicePortType.getAnnualAverageExchangeRatesAsync(SweaWebService.getAnnualAverageExchangeRatesRequest request)
        {
            return base.Channel.getAnnualAverageExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SweaWebService.getAnnualAverageExchangeRatesResponse> getAnnualAverageExchangeRatesAsync(int year, int month, SweaWebService.LanguageType languageid)
        {
            SweaWebService.getAnnualAverageExchangeRatesRequest inValue = new SweaWebService.getAnnualAverageExchangeRatesRequest();
            inValue.year = year;
            inValue.month = month;
            inValue.languageid = languageid;
            return ((SweaWebService.SweaWebServicePortType)(this)).getAnnualAverageExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SweaWebService.getInterestAndExchangeRatesResponse> SweaWebService.SweaWebServicePortType.getInterestAndExchangeRatesAsync(SweaWebService.getInterestAndExchangeRatesRequest request)
        {
            return base.Channel.getInterestAndExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SweaWebService.getInterestAndExchangeRatesResponse> getInterestAndExchangeRatesAsync(SweaWebService.SearchRequestParameters searchRequestParameters)
        {
            SweaWebService.getInterestAndExchangeRatesRequest inValue = new SweaWebService.getInterestAndExchangeRatesRequest();
            inValue.searchRequestParameters = searchRequestParameters;
            return ((SweaWebService.SweaWebServicePortType)(this)).getInterestAndExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SweaWebService.getLatestInterestAndExchangeRatesResponse> SweaWebService.SweaWebServicePortType.getLatestInterestAndExchangeRatesAsync(SweaWebService.getLatestInterestAndExchangeRatesRequest request)
        {
            return base.Channel.getLatestInterestAndExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SweaWebService.getLatestInterestAndExchangeRatesResponse> getLatestInterestAndExchangeRatesAsync(SweaWebService.LanguageType languageid, string[] seriesid)
        {
            SweaWebService.getLatestInterestAndExchangeRatesRequest inValue = new SweaWebService.getLatestInterestAndExchangeRatesRequest();
            inValue.languageid = languageid;
            inValue.seriesid = seriesid;
            return ((SweaWebService.SweaWebServicePortType)(this)).getLatestInterestAndExchangeRatesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SweaWebServiceHttpSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SweaWebServiceHttpSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://swea.riksbank.se/sweaWS/services/SweaWebServiceHttpSoap12Endpoint");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SweaWebServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.SweaWebServiceHttpSoap12Endpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SweaWebServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.SweaWebServiceHttpSoap12Endpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            SweaWebServiceHttpSoap12Endpoint,
        }
    }
}
